package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"

	"github.com/Am1rArsalan/kelvin-green/graph/model"
)

// GetWeather is the resolver for the getWeather field.
func (r *queryResolver) GetWeather(ctx context.Context, latitude string, longitude string) (*model.Weather, error) {
	weather, err := r.service.GetWeatherData(latitude, longitude)
	if err != nil {
		return nil, errors.New("Failed to get weather data")
	}

	return weather, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
