// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Daily struct {
	ApparentTemperatureMax   []*float64 `json:"apparentTemperatureMax,omitempty"`
	ApparentTemperatureMin   []*float64 `json:"apparentTemperatureMin,omitempty"`
	Sunrise                  []*string  `json:"sunrise,omitempty"`
	Sunset                   []*string  `json:"sunset,omitempty"`
	Time                     []*string  `json:"time,omitempty"`
	WeatherCode              []*int     `json:"weatherCode,omitempty"`
	Temperature2mMax         []*float64 `json:"temperature2mMax,omitempty"`
	Temperature2mMin         []*float64 `json:"temperature2mMin,omitempty"`
	WindDirection10mDominant []*float64 `json:"windDirection10mDominant,omitempty"`
}

type DailyUnits struct {
	Time                   *string `json:"time,omitempty"`
	WeatherCode            *string `json:"weatherCode,omitempty"`
	Temperature2mMax       *string `json:"temperature2mMax,omitempty"`
	Temperature2mMin       *string `json:"temperature2mMin,omitempty"`
	ApparentTemperatureMax *string `json:"apparentTemperatureMax,omitempty"`
	ApparentTemperatureMin *string `json:"apparentTemperatureMin,omitempty"`
	Sunrise                *string `json:"sunrise,omitempty"`
	Sunset                 *string `json:"sunset,omitempty"`
}

type Hourly struct {
	Time               []*string  `json:"time,omitempty"`
	Temperature2m      []*float64 `json:"temperature2m,omitempty"`
	RelativeHumidity2m []*float64 `json:"relativeHumidity2m,omitempty"`
}

type HourlyUnits struct {
	Time               *string `json:"time,omitempty"`
	Temperature2m      *string `json:"temperature2m,omitempty"`
	RelativeHumidity2m *string `json:"relativeHumidity2m,omitempty"`
}

type Query struct {
}

type Weather struct {
	Latitude             *float64     `json:"latitude,omitempty"`
	Longitude            *float64     `json:"longitude,omitempty"`
	GenerationTimeMs     *float64     `json:"generationTimeMs,omitempty"`
	UtcOffsetSeconds     *int         `json:"utcOffsetSeconds,omitempty"`
	Timezone             *string      `json:"timezone,omitempty"`
	TimezoneAbbreviation *string      `json:"timezoneAbbreviation,omitempty"`
	Elevation            *float64     `json:"elevation,omitempty"`
	HourlyUnits          *HourlyUnits `json:"hourlyUnits,omitempty"`
	Hourly               *Hourly      `json:"hourly,omitempty"`
	DailyUnits           *DailyUnits  `json:"dailyUnits,omitempty"`
	Daily                *Daily       `json:"daily,omitempty"`
}
